### PR TITLE
Refactoring Peyton_scatterplot.py

### PR DESCRIPTION
**Pull request by uid106**
CHANGES TO FILE "Peyton_scatterplot.py"
- Using csv.DictReader to reference columns by name for readability
- List comprehension added for concise code and no explicit loop

Code refactoring suggested by: https://chatgpt.com/share/66fa9251-00ac-8005-aa92-e5a4e99921ee

### CODE REVIEW

**Comment by uid106** [comment]
- Added documentation to variables
- Describe loop structure
- Describe conditional conditions 
- Overall documentation additions 

Documentation changes added based upon: https://chatgpt.com/share/66fa995d-4704-8005-8ddf-27241b21b708

**Comment by uid106** [comment]
CHANGEES TO FILE "Peyton_authorsFileTouches.py"
- Renamed variables for clarity in understanding code
- Added comments to explain sections of code
- Improved error handling

Changes added based upon: https://chatgpt.com/share/66fa9cc1-4520-8005-8496-4c43929731ac

**Comment by krain0** [comment]
> CHANGES TO FILE "Peyton_scatterplot.py"
> 
> * Using csv.DictReader to reference columns by name for readability
> * List comprehension added for concise code and no explicit loop
> 
> Code refactoring suggested by: https://chatgpt.com/share/66fa9251-00ac-8005-aa92-e5a4e99921ee

I agree that the changes you made improved the readability of the code, especially referencing the columns by name rather than relying on them being in a specific order. [ChatGPT recommends](https://chatgpt.com/c/67037913-a4dc-8000-a274-9878ab91c92b) adding some error/exception handling, but I don't think this is really necessary for a relatively short program like this which is run interactively, where crashing on exceptions seems completely fine to me. Since it was already functional, it looks ready to merge.

**Comment by krain0** [comment]
> CHANGES TO FILE "Peyton_CollectFiles.py"
> 
> * Added documentation to variables
> * Describe loop structure
> * Describe conditional conditions
> * Overall documentation additions
> 
> Documentation changes added based upon: https://chatgpt.com/share/66fa995d-4704-8005-8ddf-27241b21b708

Other than the lack of documentation, I think the original code was straightforward and effective. The documentation you added looks accurate, and is very informative. It will be especially helpful for those (like me), who don't work with python too much. Overall, I think this is a good addition that clarifies the purpose of the code and will make it easier for others to contribute.

**Comment by krain0** [comment]
> CHANGEES TO FILE "Peyton_authorsFileTouches.py"
> 
> * Renamed variables for clarity in understanding code
> * Added comments to explain sections of code
> * Improved error handling
> 
> Changes added based upon: https://chatgpt.com/share/66fa9cc1-4520-8005-8496-4c43929731ac

Renaming the variables was very effective in making the section of code easier to understand. The original variable names were not very descriptive at all, and were somewhat confusing especially if you haven't worked with JSON or making HTTP requests. The comments you added were also helpful in making the intent of the code more clear.

Finally, I think the added context in the error message will be useful for users of the script just in case the exception itself doesn't make it clear that the program encountered something unexpected and should be re-run. 

All of your changes look good to me, feel free to merge this PR once you've looked everything over.

**Pull request merged**
